<?php

namespace Database\Seeders;

use App\Models\SpCedulasModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpCedulaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events=[
            //Huaje, sin lengua
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'1',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>n\'i<sup>4</sup>n\'i<sup>4</sup></b>: lengua <b>dibaku</b>, cuicateco de Santa María Pápalo </li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'2',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>pemb</b>: lengua <b>ombeayiüts</b> de San Mateo del Mar; término genérico para Leucaena spp.</li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'3',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>tnúndétè</b>: lengua <b>tnu’un dau</b>, mixteco de Tilantongo</li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'4',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>yaglia</b>: lengua <b>dixdà</b>, zapoteco de Mitla </li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'5',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>yka nda’ jwi’ya, kwilyo’o</b>:  lengua <b>cha’ jna’a</b>, chatino de Panixtlahuaca; término específico para “huaje del valle de Oaxaca”; etimología: ‘árbol huaje tuza?’, ‘su espos@’</li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'6',   'ced_audio'=>'',    'ced_codigo'=>'<li><b>huāxin</b>: <b>náhuatl</b> de la Cuenca de México, siglo XVI</li>'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'2','ced_order'=>'7',   'ced_audio'=>'',    'ced_codigo'=>'<!--2NomComun--> Huaje'],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'3','ced_order'=>'8',   'ced_audio'=>'',    'ced_codigo'=>'<!--3NomCient--> <i>Leucaena esculenta</i> (Moc. & Sessé ex DC.) Benth '],
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'12',  'ced_audio'=>'',    'ced_codigo'=>'<div class="py-0 ps-0 center" style="color: #CDC6B9; width:120%;"> <i class="bi bi-arrow-left-circle" style="font-size: 170%; cursor: pointer;"></i> <img src="https://i.ytimg.com/vi/pj_9slUf3E0/maxresdefault.jpg"   style="max-height: 200px;padding:5px;"> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZzIYXa3Gecstc5iR1e054u4jFPaKnjcLS1Q&s" style="max-height: 200px;padding:5px;"><i class="bi bi-arrow-right-circle" style="font-size: 170%; cursor: pointer;"></i> </div>'],

            //Huaje1, lengua español2,
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'4','ced_order'=>'9',   'ced_audio'=>'',    'ced_codigo'=>'<!--4distri--> Centro y sur de México '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'5','ced_order'=>'10',  'ced_audio'=>'',    'ced_codigo'=>'<!--5habitat--> Crece en bosques tropicales caducifolios y en su transición a bosques de encino; las poblaciones silvestres se ubican en la cuenca alta del Balsas en Oaxaca, Puebla y Guerrero'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'11',  'ced_audio'=>'',    'ced_codigo'=>'<!-- 6HnatEtno--> Las semillas de este árbol son un alimento importante en Oaxaca. También se consumen las hojas tiernas, las flores e incluso la goma que produce el tronco en respuesta a algunos parásitos. En los mercados de esta ciudad encontrarás en venta manojos de vainas de huaje de octubre a marzo; las semillas se comen frescas como verdura y también secas, tostadas y molidas. Esta especie ha sido seleccionada desde la antigüedad como árbol de huerto, propagando las semillas con un contenido más bajo de mimosina. También llamado leucenol, éste es un aminoácido tóxico con una estructura química similar a la tirosina, que forma parte de nuestras proteínas. La mimosina es una defensa de la planta contra los animales herbívoros.', 'ced_audio'=>''],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'13',  'ced_audio'=>'',    'ced_codigo'=>'<!-- 6HnatEtno--> En diversas lenguas originarias, el nombre de Oaxaca se refiere siempre al huaje. Nuestra ciudad se nombra Lua y Lulá’ en las lenguas zapotecas, Nunduva en mixteco y Huāxacac en náhuatl, relacionándose en todos los casos con este árbol. El Códice Mendocino es un manuscrito elaborado en la década de 1540 en la Ciudad de México, que incluye una lista de poblaciones que pagaban tributo a la Triple Alianza. Entre ellas aparece Oaxaca, representada por el glifo de un cerro coronado por una cabeza humana con dos ramas de huaje en vaina.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'14',  'ced_audio'=>'',    'ced_codigo'=>'<!-- 6HnatEtno--> Además de servir como alimento, hoy día se fabrican collares y otros adornos artesanales con las semillas secas del huaje, de color natural o teñidas. Por ser especies fijadoras de nitrógeno, por ser árboles resistentes a sequía y por ser fuentes de forraje para el ganado, diversos miembros del género Leucaena son plantados en campañas de reforestación para recuperar suelos empobrecidos en regiones tropicales secas de África y Asia. Seguramente también nos serán útiles en México para diseñar sistemas agroforestales a futuro, en suelos erosionados actualmente improductivos.'],
            //Huaje1, lengua zapoteco8,
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'4','ced_order'=>'9',   'ced_audio'=>'',    'ced_codigo'=>'<!--4distri--> Centro y sur de México '],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'5','ced_order'=>'10',   'ced_audio'=>'Huaje_Didxaza_01.ogg', 'ced_codigo'=>"<!--5habitat--> <b>Layú ra ribani ne riguibaxigaani</b> Riroobani lu gui’xhi’ tropical caducifolio ne lu ra zeyacani gui’xhi’ encino; ca gui’xhi’di’ nuucani lu Cuenca alta del Balsas Guidxi Lula’, Puebla ne Guerrero."],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'11',   'ced_audio'=>'Huaje_Didxaza_02.ogg', 'ced_codigo'=>"<!-- 6HnatEtno--> <b>Información histórica ne etnobiológica</b>ca biidxi’ xti’ yagaga’di’ nácacani guendaró ni jmá risaca ni nuu Lula’. Laca randa rócabe ca bandaga ri’ni’, ca guie’ ne zaqueca ca goma ni ribendú ca tronco runi caadxi parásito. Ndaani’ ca luguiaa xti’ guidxidi’ zadxelalu’ cadoo be’za’ huaje lu ca beeu, octubre ra chinda ne hugaanda marzo; nayaa nga rócabe ca biidxi’di’ sica verdura ne zaqueca rócabecani nabidxi, naxhuxhu ne guiuutu’cani. Laani ma’ xadxí nga huabícabeni sica yagaga’ huerto; ra cadale ne carechená’ ca biidxi’ ne huaxie’ mimosina. Ne laca la’ni leucenol, ndi’ la, nácani ti aminoácido dxaba’ ni napa ti estructura química sicasi naca tirosina, ni naca ne ca proteína xti’nu. Mimosinadi’ nácani xiixa ni rapa ne ni rusilá ca yagahuiini’ ti qué gó mani’ laaca’."],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'13',   'ced_audio'=>'Huaje_Didxaza_03.ogg', 'ced_codigo'=>"<!-- 6HnatEtno--> Lu xtale diidxa’ huala’dxi’, lá Guidxi Lula’ dunabepe’ nga rabicabe laa huaje. Xquidxinu rabicabe laa Lua ne Lula’ lu Didxazá, Nunduva lu mixteco ne Huāxacac lu náhuatl, sicatiicasi ruchaagacabe laa ne yagaga’di’. Códice Mendocino nácani ti gui’chi’ diidxa’ ni guca’ lu ti guixhiaapa gaayu’ gayuaa chupa lategande iza ndaani’ Guidxi Zaguita (México), ni né ti ludoo lá ca Guidxi ni gudixeca’ ca ni guca ’ Triple Alianza. Lade ca ndi’ zeeda lá Lula’, bitieecabe laa lu gui’chi’di’ naca ti dani ra dxi’ba’ ti ique binni lu ne chupa yaganá’ xti’ huaje sica vaina."],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'14',   'ced_audio'=>'Huaje_Didxaza_04.ogg', 'ced_codigo'=>"<!-- 6HnatEtno--> Huaxa niru riquiiñe’ni sica guendaró, yanna ma’ runicabe biga’ ne xcaadxi adorno ne ca biidxi’ nabidxi huaje, die’ o cadi die’. Runi ti nácacani ca ni ruguuca’ nitrógeno, runi nácaca’ yagaga’ nadipala’dxi’ lu gusibá ne runi nácaca’ ca ni rudii guendaró ni gó yuze, xtalepe’ sica ca Leucaena huaguzuhuaacabe laaca’ lu ca dxiiña’ reforestación ni ruyubinécabe guilá ca layú cayaana nadachi lu ca región tropical nabidxi ni nuu África ne Asia. Zandaca Guidxi Zaguita zaquiiñe’ni laanu ti quixhechaahui’nu ca dxiiña’ agroforestale ni gaca’ lu ca dxi zedayubaru’, lu ca layú cayati ne cunitica’ xhabaládica’ ni yannadi’ ma’ qué rudiica’ gaxti’ ne ma’ qué zanda gaca’ dxiiña’ luca’."],
            //Huaje1, Huave7
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'2','ced_order'=>'7',   'ced_audio'=>'',  'ced_codigo'=>'<b>Mi nüt nej</b>: Napajteam<br>Napajteam (wüx ombeayiüts, San Mateo del Mar)'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'3','ced_order'=>'8',   'ced_audio'=>'',  'ced_codigo'=>'<!--3NomCient--> <b>Mi nüt nej niüng ajngot miün</b>:  <i>Leucaena esculenta</i> (moc. & Sesse ex DC. ) Benth.<br><b>Akualaats xiül</b>: FABACEAE'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'4','ced_order'=>'9',   'ced_audio'=>'',  'ced_codigo'=>'<!--4Distri--><b>Iüt niüng ajlüy</b>: pinowan aton kawak México'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'5','ced_order'=>'10',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 5Habitat--> <b>Niüng atang</b>: Atang tixiül niüng ajtean aop wüx ajngot nakind (üm neat) kandom wüx witiüw neat atang tixiül niüng ajlüy kiriw nakats iüt; niüng ajntsopiw aaga xiül küy apdom maxomats wüx omal mi tiük lam Balsas namong Tipajteam, Puebla akiiüb Guerrero.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'11',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat --><b>Andeaküw mixejchiiüts tanomb andüy wüx aaga xiül kiaj</b>: aaga osab a xiül kam netam ajlüy nüeteran tiül Tipajteam. Aton nüeteran naliw aopnej, mi mbaj nej, akiiüb mi yow nej a omeats xiül. Tiül mi plas kambaj kam apmixomb teajnap noik netsaag aong a napajteam wüx tengueal üm neat, aleamb gajpawüw kaw kandom ajmelich al noik neat aleam tiül arej kaw; aaga osaab nej nüeteran wüx aliün mateaik, aton nawag, akiiüb xelen, tengüa nenchiül. Aaga xiül kam larriüdaran, ajngot miün napiürüch apdom müeteran, ajchiw mexeyay naag osaab nej napateay angag, aton asoik leucenol, agüy kam noik nangaag am tiül axomüy me sapüy atnej tirosina atiün axomats tiül mi monapaküy jats. Aaga nangag ambeol nej mewüneay ngomüt nej nimal net sox. '],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'13',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat -->Meawean andearak mi nüt nej Tipajteam, andeak deam andüy wüx napajteam. Mi kambajats asoik Lua aton Lulá wüx ombeay mixiig, Nunduva wüx mixteco, ndoj Huaxacac wüx náhuatl, nop nop minüteran andeaküw wüx aaga xiül kam. Aaga Codice Mendocino noik nawiig narangüch gajpokoik akoik miow ik miow (1540) neat tiül kambaj México, iün tiül mi nüt akas kambaj niüng angüyiw aaga Triple Alianza. Amiün tiül almajlüye Tipajteam, ajikichiay amtiül noik nanchoram tiük nayaküch kawüx noik omal nipilan makiiüb ijpüw owix napajteam naong.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'6','ced_order'=>'14',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat -->Atnej atam apdom müeteran, nganüy arangüch nandiürüig, aküleran mawag marangüch najiüt wüx osaab a napajteam, atkiaj chiüp ngua nanchoram. Kos ombas nej nesap nitrógeno, kos a xiül küy neiük tiül napatiay yow, ndoj ajiür xeyay aop üt waküx, xeyay akualaats a xiül küy napiürüch wüx mapaküjchiüw tixiül apdom mapakücherana iüt tiül mi nawag kambaj Africa, at miün Asia. Atkiay apdom metam ikootsa nengüy México mapaküjchiüts aaga iüt, tiül nawag iüt niüng la ngomapak tiül xiül.'],

            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
        ];

    foreach ($events as $event){
        SpCedulasModel::create($event);
    }
    }
}
