<?php

namespace Database\Seeders;

use App\Models\SpCedulasModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SpCedulaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $events=[
            // ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'',   'ced_audio'=>'',    'ced_codigo'=>''],
            //Huaje, lengua español2,
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'1',   'ced_audio'=>'',    'ced_codigo'=>'Nombres Indígenas'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'2',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>n\'i<sup>4</sup>n\'i<sup>4</sup></b>: lengua <b>dibaku</b>, cuicateco de Santa María Pápalo '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'3',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>pemb</b>: lengua <b>ombeayiüts</b> de San Mateo del Mar; término genérico para Leucaena spp.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'4',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>tnúndétè</b>: lengua <b>tnu’un dau</b>, mixteco de Tilantongo'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'5',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>yaglia</b>: lengua <b>dixdà</b>, zapoteco de Mitla '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'6',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>yka nda’ jwi’ya, kwilyo’o</b>:  lengua <b>cha’ jna’a</b>, chatino de Panixtlahuaca; término específico para “huaje del valle de Oaxaca”; etimología: ‘árbol huaje tuza?’, ‘su espos@’'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'7',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomInd --><b>huāxin</b>: <b>náhuatl</b> de la Cuenca de México, siglo XVI'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'8',   'ced_audio'=>'',    'ced_codigo'=>'Nombre Común'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'9',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomComun--> Huaje'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'10',   'ced_audio'=>'',    'ced_codigo'=>'Nombre científico'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'11',   'ced_audio'=>'a',    'ced_codigo'=>'<!--NomCient--> <i>Leucaena esculenta</i> (Moc. & Sessé ex DC.) Benth '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'12',   'ced_audio'=>'',    'ced_codigo'=>'Familia Botánica'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'13',   'ced_audio'=>'a',    'ced_codigo'=>'<!--Fam-->FABACEAE'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'15',   'ced_audio'=>'',    'ced_codigo'=>'Distribución Geográfica'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'16',   'ced_audio'=>'a',    'ced_codigo'=>'<!--Distri--> Centro y sur de México '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'17',   'ced_audio'=>'',    'ced_codigo'=>'Hábitat'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'18',  'ced_audio'=>'a',    'ced_codigo'=>'<!--Habitat--> Crece en bosques tropicales caducifolios y en su transición a bosques de encino; las poblaciones silvestres se ubican en la cuenca alta del Balsas en Oaxaca, Puebla y Guerrero'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'19',   'ced_audio'=>'',    'ced_codigo'=>'Información histórica y etnobiológica'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',  'ced_audio'=>'a',    'ced_codigo'=>'<!-- HnatEtno--> Las semillas de este árbol son un alimento importante en Oaxaca. También se consumen las hojas tiernas, las flores e incluso la goma que produce el tronco en respuesta a algunos parásitos. En los mercados de esta ciudad encontrarás en venta manojos de vainas de huaje de octubre a marzo; las semillas se comen frescas como verdura y también secas, tostadas y molidas. Esta especie ha sido seleccionada desde la antigüedad como árbol de huerto, propagando las semillas con un contenido más bajo de mimosina. También llamado leucenol, éste es un aminoácido tóxico con una estructura química similar a la tirosina, que forma parte de nuestras proteínas. La mimosina es una defensa de la planta contra los animales herbívoros.', 'ced_audio'=>''],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'21',  'ced_audio'=>'',    'ced_codigo'=>'<!--img1--> <div class="py-0 ps-0 center" style="color: #CDC6B9; width:120%;"> <i class="bi bi-arrow-left-circle" style="font-size: 170%; cursor: pointer;"></i> <img src="https://i.ytimg.com/vi/pj_9slUf3E0/maxresdefault.jpg"   style="max-height: 200px;padding:5px;"> <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZzIYXa3Gecstc5iR1e054u4jFPaKnjcLS1Q&s" style="max-height: 200px;padding:5px;"><i class="bi bi-arrow-right-circle" style="font-size: 170%; cursor: pointer;"></i> </div>'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'22',  'ced_audio'=>'a',    'ced_codigo'=>'<!-- HnatEtno--> En diversas lenguas originarias, el nombre de Oaxaca se refiere siempre al huaje. Nuestra ciudad se nombra Lua y Lulá’ en las lenguas zapotecas, Nunduva en mixteco y Huāxacac en náhuatl, relacionándose en todos los casos con este árbol. El Códice Mendocino es un manuscrito elaborado en la década de 1540 en la Ciudad de México, que incluye una lista de poblaciones que pagaban tributo a la Triple Alianza. Entre ellas aparece Oaxaca, representada por el glifo de un cerro coronado por una cabeza humana con dos ramas de huaje en vaina.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'23',  'ced_audio'=>'a',    'ced_codigo'=>'<!-- HnatEtno--> Además de servir como alimento, hoy día se fabrican collares y otros adornos artesanales con las semillas secas del huaje, de color natural o teñidas. Por ser especies fijadoras de nitrógeno, por ser árboles resistentes a sequía y por ser fuentes de forraje para el ganado, diversos miembros del género Leucaena son plantados en campañas de reforestación para recuperar suelos empobrecidos en regiones tropicales secas de África y Asia. Seguramente también nos serán útiles en México para diseñar sistemas agroforestales a futuro, en suelos erosionados actualmente improductivos.'],

            //Huaje1, lengua zapoteco8,
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'1',   'ced_audio'=>'',    'ced_codigo'=>'Layú ra ribani ne riguibaxigaani'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'2',   'ced_audio'=>'Huaje_Didxaza_01.ogg',    'ced_codigo'=>'Riroobani lu gui\'xhi\' tropical caducifolio ne lu ra zeyacani gui\'xhi\' encino; ca gui\'xhi\'di\' nuucani lu Cuenca alta del Balsas Guidxi Lula\', Puebla ne Guerrero.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'9',   'ced_audio'=>'',    'ced_codigo'=>'Información histórica ne etnobiológica'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'11',   'ced_audio'=>'Huaje_Didxaza_02.ogg', 'ced_codigo'=>'<!-- HnatEtno--> ca biidxi\' xti\' yagaga\'di\' nácacani guendaró ni jmá risaca ni nuu Lula\'. Laca randa rócabe ca bandaga ri\'ni\', ca guie\' ne zaqueca ca goma ni ribendú ca tronco runi caadxi parásito. Ndaani\' ca luguiaa xti\' guidxidi\' zadxelalu\' cadoo be\'za\' huaje lu ca beeu, octubre ra chinda ne hugaanda marzo; nayaa nga rócabe ca biidxi\'di\' sica verdura ne zaqueca rócabecani nabidxi, naxhuxhu ne guiuutu\'cani. Laani ma\' xadxí nga huabícabeni sica yagaga\' huerto; ra cadale ne carechená\' ca biidxi\' ne huaxie\' mimosina. Ne laca la\'ni leucenol, ndi\' la, nácani ti aminoácido dxaba\' ni napa ti estructura química sicasi naca tirosina, ni naca ne ca proteína xti\'nu. Mimosinadi\' nácani xiixa ni rapa ne ni rusilá ca yagahuiini\' ti qué gó mani\' laaca\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'13',   'ced_audio'=>'Huaje_Didxaza_03.ogg', 'ced_codigo'=>'<!-- HnatEtno--> Lu xtale diidxa\' huala\'dxi\', lá Guidxi Lula\' dunabepe\' nga rabicabe laa huaje. Xquidxinu rabicabe laa Lua ne Lula\' lu Didxazá, Nunduva lu mixteco ne Huāxacac lu náhuatl, sicatiicasi ruchaagacabe laa ne yagaga\'di\'. Códice Mendocino nácani ti gui\'chi\' diidxa\' ni guca\' lu ti guixhiaapa gaayu\' gayuaa chupa lategande iza ndaani\' Guidxi Zaguita (México), ni né ti ludoo lá ca Guidxi ni gudixeca\' ca ni guca \' Triple Alianza. Lade ca ndi\' zeeda lá Lula\', bitieecabe laa lu gui\'chi\'di\' naca ti dani ra dxi\'ba\' ti ique binni lu ne chupa yaganá\' xti\' huaje sica vaina.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'14',   'ced_audio'=>'Huaje_Didxaza_04.ogg', 'ced_codigo'=>'<!-- HnatEtno--> Huaxa niru riquiiñe\'ni sica guendaró, yanna ma\' runicabe biga\' ne xcaadxi adorno ne ca biidxi\' nabidxi huaje, die\' o cadi die\'. Runi ti nácacani ca ni ruguuca\' nitrógeno, runi nácaca\' yagaga\' nadipala\'dxi\' lu gusibá ne runi nácaca\' ca ni rudii guendaró ni gó yuze, xtalepe\' sica ca Leucaena huaguzuhuaacabe laaca\' lu ca dxiiña\' reforestación ni ruyubinécabe guilá ca layú cayaana nadachi lu ca región tropical nabidxi ni nuu África ne Asia. Zandaca Guidxi Zaguita zaquiiñe\'ni laanu ti quixhechaahui\'nu ca dxiiña\' agroforestale ni gaca\' lu ca dxi zedayubaru\', lu ca layú cayati ne cunitica\' xhabaládica\' ni yannadi\' ma\' qué rudiica\' gaxti\' ne ma\' qué zanda gaca\' dxiiña\' luca\'.'],

            //Huaje1, Huave7
            //['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'',   'ced_audio'=>'',  'ced_codigo'=>''],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'1',   'ced_audio'=>'',  'ced_codigo'=>'Mi nüt nej'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'2',   'ced_audio'=>'A',  'ced_codigo'=>'Napajteam<br>Napajteam (wüx ombeayiüts, San Mateo del Mar)'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'3',   'ced_audio'=>'',  'ced_codigo'=>'Mi nüt nej niüng ajngot miün'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'4',   'ced_audio'=>'a',  'ced_codigo'=>'<i>Leucaena esculenta</i> (moc. & Sesse ex DC. ) Benth.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'5',   'ced_audio'=>'',  'ced_codigo'=>'Akualaats xiül'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'6',   'ced_audio'=>'a',  'ced_codigo'=>'FABACEAE'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'7',   'ced_audio'=>'',  'ced_codigo'=>'Iüt niüng ajlüy'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'8',   'ced_audio'=>'a',  'ced_codigo'=>'pinowan aton kawak México'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'9',   'ced_audio'=>'',  'ced_codigo'=>'Niüng atang'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'10',   'ced_audio'=>'a',  'ced_codigo'=>'Atang tixiül niüng ajtean aop wüx ajngot nakind (üm neat) kandom wüx witiüw neat atang tixiül niüng ajlüy kiriw nakats iüt; niüng ajntsopiw aaga xiül küy apdom maxomats wüx omal mi tiük lam Balsas namong Tipajteam, Puebla akiiüb Guerrero.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'1','ced_order'=>'11',   'ced_audio'=>'',  'ced_codigo'=>'Andeaküw mixejchiiüts tanomb andüy wüx aaga xiül kiaj'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'12',   'ced_audio'=>'a',  'ced_codigo'=>'Aaga osab a xiül kam netam ajlüy nüeteran tiül Tipajteam. Aton nüeteran naliw aopnej, mi mbaj nej, akiiüb mi yow nej a omeats xiül. Tiül mi plas kambaj kam apmixomb teajnap noik netsaag aong a napajteam wüx tengueal üm neat, aleamb gajpawüw kaw kandom ajmelich al noik neat aleam tiül arej kaw; aaga osaab nej nüeteran wüx aliün mateaik, aton nawag, akiiüb xelen, tengüa nenchiül. Aaga xiül kam larriüdaran, ajngot miün napiürüch apdom müeteran, ajchiw mexeyay naag osaab nej napateay angag, aton asoik leucenol, agüy kam noik nangaag am tiül axomüy me sapüy atnej tirosina atiün axomats tiül mi monapaküy jats. Aaga nangag ambeol nej mewüneay ngomüt nej nimal net sox. '],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'13',   'ced_audio'=>'a',  'ced_codigo'=>'Meawean andearak mi nüt nej Tipajteam, andeak deam andüy wüx napajteam. Mi kambajats asoik Lua aton Lulá wüx ombeay mixiig, Nunduva wüx mixteco, ndoj Huaxacac wüx náhuatl, nop nop minüteran andeaküw wüx aaga xiül kam. Aaga Codice Mendocino noik nawiig narangüch gajpokoik akoik miow ik miow (1540) neat tiül kambaj México, iün tiül mi nüt akas kambaj niüng angüyiw aaga Triple Alianza. Amiün tiül almajlüye Tipajteam, ajikichiay amtiül noik nanchoram tiük nayaküch kawüx noik omal nipilan makiiüb ijpüw owix napajteam naong.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'1', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'14',   'ced_audio'=>'a',  'ced_codigo'=>'Atnej atam apdom müeteran, nganüy arangüch nandiürüig, aküleran mawag marangüch najiüt wüx osaab a napajteam, atkiaj chiüp ngua nanchoram. Kos ombas nej nesap nitrógeno, kos a xiül küy neiük tiül napatiay yow, ndoj ajiür xeyay aop üt waküx, xeyay akualaats a xiül küy napiürüch wüx mapaküjchiüw tixiül apdom mapakücherana iüt tiül mi nawag kambaj Africa, at miün Asia. Atkiay apdom metam ikootsa nengüy México mapaküjchiüts aaga iüt, tiül nawag iüt niüng la ngomapak tiül xiül.'],


            //Sabino2, sin lengua
            ['ced_autor'=>'1','ced_lengua'=>'1', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'10',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 1NombresLengua --><li><b>yag guitz</b> (lengua dixdà, zapoteco de Mitla) </li> <li><b>nuyúkún</b> (lengua sahin sau, mixteco de San Miguel el Grande) </li>'],
            //Sabino2, español2
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 2NomCom --> Sabino, Ahuehuete'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 3NomCient --> <i>Taxodium mucrunatum</i> Ten.<br><b>Familia</b>: Cupressaceae'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'40',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 4Distri --> México y Guatemala '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'50',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 5Habitat --> Crece en ciénagas y a la orilla de ríos y arroyos, en valles intermontanos por encima de 1500 msnm'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'60',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat --> El ejemplar más destacado de esta especie, llamado “Árbol del Tule”, crece en la comunidad zapoteca de Santa María del Tule, a once kilómetros al oriente de nuestra ciudad de Oaxaca de Juárez. Tiene una edad estimada en cerca de dos mil años; los estudios arqueológicos indican que la comunidad ya existía en ese lugar antes de esas fechas, por lo que es posible que el árbol haya sido plantado o protegido por sus habitantes. Es probable que la vegetación original del terreno que hoy ocupa nuestra ciudad, incluyendo parte del actual JEB, haya sido un bosque de galería dominado por sabinos. Por ello elegimos la madera de esta especie para las esculturas y las bancas de descanso que encontrarás a lo largo de tu recorrido en el Jardín.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat --> En la literatura oaxaqueña encontramos relatos acerca del origen del Árbol del Tule que son presentados como antiguas leyendas, pero que probablemente surgieron de la pluma de los autores románticos de principios del siglo pasado. Una de estas versiones narra cómo el sabino fue plantado por Quetzalcóatl, o por un profeta llamado Pecocha que supuestamente venía de Nicaragua y a quien también se atribuye la antigua cruz de madera conservada en Huatulco. Según otro relato, hace mucho tiempo la gente de la región del Tule cortaba árboles y mataba animales indiscriminadamente. Con el tiempo, los períodos de sequía se acentuaron y la población comenzó a resentir la falta de agua. Condoy, valeroso caudillo del pueblo ayuuk (mixe), pasó un día por allí, de regreso a las montañas. Al verlo, mujeres, hombres y animales imploraron su ayuda.  Conmovido por su sufrimiento, aunado al arrepentimiento que mostraban, tomó el bastón que llevaba consigo y lo enterró. Se formaron así nubes densas que finalmente descargaron abundante lluvia, dando fin a la sequía. Del bastón comenzaron a brotar ramitas y alrededor de él se formó un humedal. Condoy dejó su bastón, convertido en el gran ahuehuete, como señal de su presencia. '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 6HistNat --> Antes de figurar en la literatura romántica del periodo porfiriano, los sabinos ya tenían un papel protagónico en las culturas de Oaxaca desde la antigüedad. Aparecen en los mitos de origen de la civilización mixteca. El Códice Yuta Tnoho (antes conocido como Códice Vindobonense), manuscrito precolombino que procede de la Mixteca Alta de Oaxaca, muestra a la pareja humana primordial naciendo del tronco de un sabino.'],

            //Sabino2, Huave7
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 2NomCom --> <b>Mi nüt nej</b>: Sabino, ahuehuete'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 3NomCient --> <b>Mi nüt nej niüng ajngot</b>: Taxodium mucronatum Ten.<br><b>Akualaats xiül</b>: CUPRESSACEAE'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'40',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 4Distri --> <b>Iüt niüng ajlüy</b>: Mexico, atiün Guatemala.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'50',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 5Habitat --><b>Niüng atang</b>: Atang tiül xeyay yow, wüx ombeay lam, niüng aküir yow, tiül najmiük iüt ayeinej tiük, tiül iüt ajiür gajpokoik akoik miow (1500) metro wüx omal ndek. '],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'60',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat --><b>Andeaküw mixejchiiüts tanomb andüy wüx aaga xiül keaj</b>: aaga manajnsop mi nüt nej “Arbol del Tule”, atang tiül mi kambaj mixiig mi nüt nej “Santa Maria del Tule”, gajpanoik km andüy nonüt oküiaj Tipajteam. Ajiür xeyay mi neat nej atüch nimiow akoik miow neat (2000), ajküw monjaw wüx andeaküw ajüik lapeayiw kiaj tiül kambaj mbas nejiw mixiig, atkiay apdom mapiüngats aaga xiül kiaj napiürüch, at miün mi nipilan kambaj tea majiürüwa xiül. Apndom marang ton aaga ajküw xiül tiül aaga iüt niüng ajlüy nganüy Tipajteam at miün aaga niüng ajlüy nganüy JEB, tarang noik tixiül niüng xeyay sabino, abdom marang a xiül kiaj arangüch neol, iskün niüng chetejaran tiül jardín wüx mapeayiw monjüy.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat -->Tiül mi nawiig Tipajteam axomats nandearak andüy wüx mi xiül Tule leaw andearak tanomb. Miün tiül andeaküw ajküw nipilan tiül namong koik miow neat. Noik tiül mondeak küy ajüik aaga sabino apiür Quetzalcoatl, aton andearak apiür nop nendeak leaw andeak Teat Dios minüt nej Pecocha miün chek Nicaragua, aton ne kiün tanomb mi xiül cruz alnenguien Huatulco. Al noik nandearak, lamajiür nüt, ajküw nipilan nawüw Tule ambiyaüwa xiül atiün aga nimal, ngomapiengüw wüx. Tamong a nüt, texeyay a nerrar, nawag a iüt, ngoma tüch nejiwe yow. Condoy nop ngo membol omeats miün tiül mi kambaj ayuuk (mixe), tatüche nüt tamong chek kiaj, wüx andilil andüy tiül tiük. Wüx tajawüw nej montaj, monxey, nimal, tatüniw mambeol nejiw. Tarreg nej omeatsnej nael teamamongochiw, aton tajaw amix omeajtsüw, tayar mi xiül al tewix nej tasamapiür tiül iüt. Kawüx kajnchiüt nadamdam oik niüng tatsambich napak ijchiür, tandondoch a nael tea mamongochiw ngojlüy yow. Aaga xiül apiür tsatsat, tajnsop xeyay owix nej, atankiay tajlüy yow kiaj takats a iüt ayei tiüt aaga xiül. Condoy atkiay taküeat kiaj mi xiül nej, tarangüy noik nadam xiül ahuehuete, niüng ajikich nej tajüy kiaj. '],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat --> Wüx nganaow mejikichiay tiül nawiig wüx ajlaüy Porfirio, ajküw xiül sabino tanomb landearak xeyay wüx xiül kiaj tiül mikambaj Tipajteam. Ajntsop miün tiül andeaküw mixtecos. Aaga Codice Yuta Tnoho (tanomb Codice Vindobonense) noik nawiig precolombino miün tiül mixteca alta Tipajteam, ajikich ijpüw nipilan nekiiübayej tea wejkiajow miün tiül omeats a xiül kam sabino.'],

            //Sabino2,zapoteco8
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 2NomCom --><b>yag guitz</b> (lengua dixdà, zapoteco de Mitla)  <br><b>nuyúkún</b> (lengua sahin sau, mixteco de San Miguel el Grande) '],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 3NomCient --><b>Científicamente la la’ni</b>: <i>Taxodium mucronatum</i> Ten.<br><b>Lisaa xti’</b>: CUPRESSACEAE'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'40',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 4Distri --><b>Ca layú ra nuuni</b>: México y Guatemala '],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'50',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 5Habitat --><b> Layú ra ribani ne riguibaxigaani</b>:  Riroobani lu ca gue’la’ ne ruaanisa xti\' ca guiigu\' ne ra cuxooñe’ nisa, lu ca valle nuu lade ca dani ni ridi’di’ luguiá’ que ti guixhiaapa gaayu’ gayuaa mnsm.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'60',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat --><b>Información histórica ne etnobiológica</b>: ni niru jmá runibia’cabe ladecani la, lá’ “yagaga\' o yaga Tule”, riroobani ndaani\' Guidxi binnizá Santa María Tule, bia’ lu chii ne tobi Kilómetro neza oriente xti\' Guidxi Lula\' xti’nu. Nápani bia’ chupa guixhiaapa gayuaa iza; ca estudio Arqueológico huayaca rini’ca’ guidxidi’ maca nuuni niru ca dxidi’, ngueruni zandaca ca binni guidxidi\' nga ni bizuhuaa o gúpaca’ yagaga\'di\'. Zandaca ca gui’xhi\' naga’ xti\' xtipe’ layú ra yannadxi zuba xquidxinu, ne zaqueca ti ndaa layú ni yanna naca JEB, gucaca ti gui’xhi’ naro’ba’ ni gupa xtalepe\' yagaga\' sabino. Ngueruni ribinu ca yaga xti’ yagaga\'di’ ni gaca’né ca escultura ne ca bangu’ ra rizila\'dxi\' binni ni zadxe’lu’ lu guidubinaca ra zizalu’ zigudiilu’ bieque lu jardindi’.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat -->Lu ca diidxa\' cá xti’ gudxi Lula’ zadxelanu cá diidxa\' ni rini’ xi sica biale Yagaga\' Tule, ni rului\'cabe laaca’ sica didxayooxho’, huaxa zandaca bialeca’ luná’ ca binnirucaa ni rabicabe Románticos, ca ni biuu lu ca niru iza xti\' gayuaa iza deru’ gudi’di’. Tobi ca diidxa\'di’ rini’ xi sica bizuhuaa Quetzalcóatl yagaga’ sabinodi’ o ti profeta ni biree lá Pecocha, ni nácabe binni Nicaragua laa, ni nácabe laca laa nga biza’ Cruz ni ma’ napa xtale iza cayaapa’ Huatulco. Nuu xti diidxa\' ni ná, raca xtale iza ca binni guleza guidxi Tule, bigaca\' yagaga’ ne qué ñuniluca’ bitixhaata’ca’ mani’. Ra zedi’di’ iza, bidale ca xhi gusibá ne guidxidi’ bedaguinaase’ guendariaadxa’ nisa laaca’. Condoy, binni nadxibalú xaique guidxi ayuuk (mixe), ti dxi gudi’di’ nezaque, ra cabigueta\' lu dani, ca gunaa, nguiiu ne mani’ ra biiya’ca’ laabe, gunabaca’ gacanebe laaca\'. Biaabe laaca’ ra biiyabe cayuuba’ ne cayaca arrepentirca’, gucuaabe dximba ni canacaabeque ne bitaabibeni layú. Zaque nga bia’ xtale zá nananadondo ni bedagusabaca’ ti nisaguiero’, ni bedagucueezadxí gusibaque. Lu dximbaque guchendú caadxi biiutu ne guidubi bieque xti\'ni bia’ ti gudxa. Bisaana Condoy dximba xti\', naca ahuehuetero’, sicasi duuba’ xti\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'2', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 6HistNat -->Niru guedaguihuini lu ca diidxa\' rabicabe romántica lu xhi biree lá porfiriano, ca yaga sabino ma’ napa xtale iza, dunabepe\' nga huayapaca’ ti xhisaca lu xquenda ne xpia’ guidxi Lula\', canini cá iza yooxho\'. Rihuinica’ lu ca mito rini’ sica bizulu civilización Mixteca alta xti\' Lula\', rului’ niru chupa miati’ (ti gunaa ne ti nguiiu) cayale lu birungu, xtiixhi\' ti yagaga\' sabino.'],

            //Grana4, español2
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'10',    'ced_audio'=>'', 'ced_codigo'=>'<!--1a --><b>Nombre y familia</b>:<br><i>nombre en el siglo XVI</i>:<b>pèa</b>: zapoteco de Tlacochahuaya<br>'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',    'ced_audio'=>'', 'ced_codigo'=>'<!--1b --><i>nombres actuales</i>:<br><b>baguùu’g</b>: zapoteco de San Lucas Quiaviní <br><b>beguug </b>: zapoteco de Mitla<br><b>bwa</b>: zapoteco de Chichicapan <br><b>má biǎa</b>: (‘animal nopal’): zapoteco de San Juan Mixtepec<br>'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',    'ced_audio'=>'', 'ced_codigo'=>'<!--2 -->La grana es un animal pequeño que crece sobre los nopales. Es más chico que un grano de maíz y un poco más grande que una lenteja. Las chinches que nos pican y las cigarras que suenan en temporada de calor son parientes lejanos de la grana. Esta familia de insectos se distingue porque todos tienen una boca que chupa, ya sea la savia de una planta o la sangre de un animal. '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'40',    'ced_audio'=>'', 'ced_codigo'=>'<!--3 -->La grana tiene diez parientes cercanos que crecen silvestres en el monte desde Argentina hasta Texas, pero ella fue la única que domesticaron nuestros antepasados. Domesticada quiere decir que los humanos la criamos a lo largo de mucho tiempo, escogiendo la que nos servía mejor. Criar la grana fue un gran logro de los pueblos originarios del sur de México porque ella nos da un colorante rojo muy apreciado desde hace miles de años. Se le llama “grana fina” para distinguirla de sus parientes silvestres. Al igual que ella, sus parientes necesitan chupar la savia de los nopales para vivir. A diferencia de ellos, que tienen una cubierta de cera blanca, gruesa y pegajosa, la cubierta de la grana fina es como un polvo, también blanco, pero es mucho más fácil de desprender.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'50',    'ced_audio'=>'', 'ced_codigo'=>'<!--4 --><h4>¿Dónde vive?</h4>La grana fina sólo crece en algunos nopales cultivados, plantas que también fueron domesticadas en México en la antigüedad. Una de ellas se conoce en Oaxaca como “nopal San Gabriel”, y la otra se nombra “nopal de Castilla”, si bien no es originaria de España. Cultivamos los dos nopales en este Jardín, donde los puedes distinguir con facilidad porque las pencas del nopal San Gabriel son de color verde lustroso y sus flores son anaranjadas, mientras que las pencas del nopal de Castilla son opacas y azulosas, y sus flores son amarillas. Las espinas de los dos nopales fueron eliminadas por selección humana, para hacer más fácil la cría de la grana.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'60',    'ced_audio'=>'', 'ced_codigo'=>'<!--5 -->Los nopales domesticados donde se cría la grana fina son delicados, como el insecto, y sólo podemos cultivarlos en lugares templados: no aguantan el calor de la tierra caliente ni el frío en las tierras altas. Se pudren por la humedad constante en las montañas cubiertas de neblina. En Oaxaca la grana era criada anteriormente en la Mixteca y en el Valle, así como en las cañadas y laderas bajas de las sierras.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',    'ced_audio'=>'', 'ced_codigo'=>'<!--6 --><h4>¿Cómo se ve? </h4>La hembra madura de la grana fina es redonda, de color blanco y está fija en el nopal. No puede moverse porque su larga boca, que parece un popote muy delgado, queda clavada en la carnita del nopal. El macho es mucho más pequeño, tiene alas y puede volar a poca distancia durante su corta vida, que sólo dura un par de días. Al nacer, tanto las hembras como los machos son muy chiquitos y lucen un color rojo brillante, antes de cubrirse de cera. Tienen patitas que les permiten caminar sobre el nopal. A medida que crecen, dejan de moverse y comienzan a producir su capa de cera blanca. Las hembras toman su forma de bolita y los machos forman un capullo en forma de tubo. Cuando maduran, salen del capullo y empiezan a volar con sus alitas. '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',    'ced_audio'=>'', 'ced_codigo'=>'<!--7 -->Como es un insecto domesticado, la grana no puede vivir sin el cuidado de la gente. Hay que protegerla de las granizadas y las lluvias fuertes. También hay que combatir con cuidado a otros insectos que se alimentan de ella, y hay que eliminar a la grana silvestre cuando aparece en el mismo nopal. La grana silvestre le gana a la grana fina, que es delicada, y mata al nopal si no la controlamos. Hay que cercar las nopaleras con estacas o con plantas espinosas para evitar que el ganado y las aves de corral muerdan las pencas y se coman a las granas. Además de cuidarlas, la gente de Oaxaca protegía a su querido insecto con rezos y ofrendas de copal y velas.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'90',    'ced_audio'=>'', 'ced_codigo'=>'<!--8 --><h4>¿Qué sabemos de su historia?</h4>Aquí en el Jardín Etnobiológico de Oaxaca hemos aprendido que la grana fue domesticada junto con los nopales para usarla como pintura sobre la piel desnuda, antes de que la gente viviera de la milpa en pueblos fijos y antes de que el pequeño animal sirviera para teñir ropa. Creemos que el nopal “de Castilla” y la grana viva fueron llevados por mar en canoas desde el sur de México hasta Sudamérica, para producir el tinte en regiones con clima seco y templado como en el Valle de Oaxaca. Allá se convirtió en el rojo preferido por los incas y otros pueblos originarios de los Andes.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'100',   'ced_audio'=>'', 'ced_codigo'=>'<!--9 -->Los documentos antiguos muestran que Oaxaca era el centro de producción de grana antes de que llegaran los europeos, pues la Mixteca y los Valles Centrales eran las únicas provincias que mandaban el tinte a Tenochtitlan, la capital mexica. Después de la invasión europea, estas mismas regiones siguieron produciendo la mayor cantidad y la mejor calidad del tinte durante trescientos años, hasta que los ingleses y alemanes comenzaron a fabricar las anilinas después de 1850. A lo largo de tres siglos, la grana de Oaxaca fue el producto del campo mejor pagado en el comercio de todo el mundo. Su producción hizo rica a nuestra región y permitió que esta ciudad creciera para ser la tercera en tamaño y riqueza en Nueva España. Solamente la Ciudad de México y Puebla eran más grandes que Oaxaca.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'200',   'ced_audio'=>'', 'ced_codigo'=>'<!--10 -->A diferencia del tabaco, el cacao y la caña de azúcar, que cultivaban los esclavos en las haciendas, la cría de la grana siempre quedó en manos de comunidades indígenas, quienes tenían los conocimientos finos y la mano de obra cuidadosa para producirla. La grana les dejó grandes ganancias a los españoles, que controlaban su comercio hacia todo el mundo. Por esta razón, el rey y el virrey y las demás autoridades protegieron a las comunidades de Oaxaca, más que en otras regiones. Gracias a eso más del 70% de la tierra en Oaxaca es ahora propiedad comunal.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'300',   'ced_audio'=>'', 'ced_codigo'=>'<!--11 -->Cuando Benito Juárez, a la edad de doce años, caminó de Guelatao a esta ciudad de Oaxaca, llegó a la casa de la familia Maza, donde su hermana Josefa trabajaba como sirvienta. El joven serrano empezó entonces a ganarse la vida trabajando en una nopalera de grana. Varios años después, esta experiencia temprana con el insecto llevó a Juárez a pensar que los comerciantes de Oaxaca se habían acostumbrado a las ganancias fáciles que dejaba la grana y por eso no se esforzaban en buscar maneras de trabajar para crear riqueza.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'400',   'ced_audio'=>'', 'ced_codigo'=>'<!--12 --> <h4>¿De dónde sale el color y qué se pinta con él?</h4>La hemolinfa en los insectos es como la sangre en nuestro cuerpo y como la sangre de otros animales. La hemolinfa de la grana contiene ácido carmínico, una sustancia compleja y estable que le da el color rojo intenso. El ácido carmínico protege a la grana de dos formas: por un lado, la protege de infecciones en su tripa. Por otro lado, el ácido carmínico sirve como un repelente fuerte contra las hormigas y otros insectos que se la comerían. '],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'500',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 13--> Usado como tinte, el ácido carmínico tiene la ventaja de que resiste al sol y al agua mejor que otros colorantes. Al teñir o pintar, se puede modificar su color: el vinagre, el jugo de limón y todo lo agrio encienden su color hacia el rojo anaranjado, mientras que la lejía de cal o ceniza lo cambia de rojo oscuro a morado. Otra ventaja de la grana es que nos protege del sol que daña a nuestra piel, una mejor protección que la de otros tintes.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'600',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 14--> En Oaxaca la grana se usa para teñir lana y seda, pues el ácido carmínico se adhiere con más facilidad a las fibras animales. Las familias tejedoras de Teotitlán y Santa Ana del Valle ocupan la grana para teñir sus sarapes y tapetes de lana, mientras que en San Pedro Cajonos se usa para teñir los rebozos de seda criolla. En varias comunidades zapotecas se acostumbraba que las mujeres vestían faldas teñidas con grana durante las fiestas, especialmente la novia que se casaba. También servía para colorear alimentos como el nicuatole, una preparación deliciosa de maíz que se parece a una gelatina en su consistencia. En todo México, los tamales de dulce se tiñen de color de rosa en recuerdo de la grana, que servía para no confundirlos con los tamales de sal.'],
            ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'700',   'ced_audio'=>'', 'ced_codigo'=>'<!-- 15--> Fuera de México, la grana se convirtió en el color favorito para los pintores y otros artistas por la variedad de tonos y la intensidad de color que da el ácido carmínico. Podemos decir que la grana oaxaqueña fue la mayor contribución de México al arte de todo el mundo. Acá en el Jardín Etnobiológico comenzamos a criar un poco de grana fina en julio de 2024, gracias al artista Édgar Jahir López Trujillo, nuestro amigo generoso. Cultivamos algunas pencas de nopal de Castilla en un espacio protegido para que las personas que nos visitan conozcan el valioso insecto, sobre todo los grupos de niños que vienen de las escuelas'],

            //Grana4, zapoteIstmo8
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'10',    'ced_audio'=>'a', 'ced_codigo'=>'<!--1a --><b>Lá ne Lisaa </b><br><i>Lá lu siglo XVI</i>:<b>pèa</b>: zapoteco de Tlacochahuaya<br>'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',    'ced_audio'=>'a', 'ced_codigo'=>'<!--1b --><i>Ca lame yanna</i>:<br><b>baguùu\'g</b>: zapoteco de San Lucas Quiaviní <br><b>beguug</b>: zapoteco de Mitla<br><b>bwa</b>: zapoteco de Chichicapan <br><b>má biǎa</b>: (‘animal nopal\'): zapoteco de San Juan Mixtepec<br>'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',    'ced_audio'=>'a', 'ced_codigo'=>'<!--2 -->Grana nga ti manihuiini\' ni rirooba\' lu ca yaga guichibiaagueta. Nahuiini\'ni jmá que ti xuba\' ne naro\'ba\' xcaadxi que ti lenteja. Ca chinche ni ruquiichi\' laanu ne ca bigarii ni runanu lu xhii guendananda\' nácaca\' lisaa ra jmá zitu xti\' ca grana. Lisaa xti\' ca mani\'di\' rihuinipe\' tu laaca\' ti ruaaca\' bia\'pe\'ca\' ti cuba\'ca\', niidxi ca yagahuiini\' o rini xti\' tuuxa mani\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'40',    'ced_audio'=>'a', 'ced_codigo'=>'<!--3 -->Chii lisaa gaxhado\' nga napa grana ni raleca\' ndaani\' gui\'xhi\' niru Argentina ne rinda hugaanda Texas, huaxa laasime nga ni bisido\' ca binni zániru Laanu. Bisido\' nga rienenu, xadxipe\' nga laanu ca binni nga bisiroobanu laa, ribinu ni jmá riquiiñe\' Laanu. Gusiroobanu grana nga tobi ca dxiiña\' naro\'ba\' bi\'ni\' ca Guidxi huala\'dxi\' nabeza neza guete\' xti\' Guidxiro\' Zaguita, ti ma\' napape\' xtale guixhiaapa iza nga rudiime laanu ti tiee naxiñá\' ni dunabepe\' rusisácanu. La\'me “grana fina”, ti zaca guanda guniba\'nu laa lade ca lisaa gui\'xhi\' xtime. Sica laame, ca lisaame laca naquiiñe\'ca\' gueca\' niidxi xti\' ca guichibiaagueta ti guibanica\', huaxa laacame, nápacame xiixa ruchii ládicame naca ne cera naquichi\', nanaande\' ne naxiguiidi\', ne ni ruchii ladi grana fina la, zedayacasi sica dé ne laca naquichi\', huaxa ma\' nagueenda nga redaguiladi\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'50',    'ced_audio'=>'a', 'ced_codigo'=>'<!--4 --><h4>¿Paraa nabezame?</h4>Grana fina lu caadxisi guichibiaagueta biidxiibacabe nga riroobame, ca yagahuiini\' ni bisiroobacabe ndaani\' Guidxiro\' Zaguita lu ca izayooxho\'. Tobi de laacani runibia\'cabe laa ndaani\' guidxi Lula\' sica “guichibiaagueta xti\' San Rafael” ne xtobicala rabicabe laa “guichibiaagueta xti\' Castilla”, necape\' cadi xti\'di\' Guidxi Españani. huaxa cadi nácadini. Guirópacani nga rudxiiba\'du rari\' ra jardindi\', ra nagueendape\' zanda gunibia\'tu laaca\' ti ca penca xti\' guichibiaagueta San Gabriel naga\' ne ruzaani\'ca\' ne nabiguitu ca guie\' xti\', ne ca penca xti\' ca guichibiaagueta Castilla la, naté ne naziaca\', ne naguchi ca guie\' xti\'ca\'. Ca guiichi xti\' guiropa\'ca\' binni nga bi\'ni\' guinitiluca\', ti zaca qué gaca\' nagana guirooba\' ca grana.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'60',    'ced_audio'=>'a', 'ced_codigo'=>'<!--5 -->Ca guichibiaagueta ni bisirooba\' binni ra rirooba\' grana fina nadaca\'ni, sicasi manihuiini\' ni rabicabe Insecto, ne ra nadxadusi nga zanda gudxiiba\'nu laaca\': qué randadi\' guibanica\' ne guendananda\' xti\' ca layú nda\' ne zaqueca ne guendanaga\'nda\' xti\' ca layú nasoo. Riuudxu\'ca\' runi gupa ni nuu lu ca dani. Lula\', dxique la ra Mixteca ne Valle nga bisiroobacabe grana, zaqueca nga lu ca cañada ne ca ladera guete\' xti\' ca sierra.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',    'ced_audio'=>'a', 'ced_codigo'=>'<!--6 --><h4>¿Xi sica rihuinime?</h4>Nagola ma\' gula xti\' grana fina nácame nabidoola, naquichi\' ne dxiichi\' nga gui\'di\'me lu guichibiaagueta. Qué randa riniibime ti ruaame ziuula\' rului\' ti popote nalase\' dabidxiichi\'ni ndaani\' la\'dxi\' xti\' guichibiaagueta. Ngola la naca jmá nahuiini\', napa xhiaa ne nachucupe\' nga ra bia\' randa ripapame lu bia\' nachucu xquendanabanime, ni rindaa bia\' chupa chonnasi gubidxa. Dunabepe\' nga nahuiini\'ca ne naxiñá\' ruzaani\' nga ca nagola zaqueca ca ngola ra raleca\' niru guidaapaca\' ne cera. Nápaca\' ñeeca\' ni rudii laaca\' ganda sa\'ca lu guichibiaagueta. Ra ma\' ziniisica\', rusaana guiniibica\' ne ruzulu gunica\' ti neza cera naquichi\'. Ca nagola ribidoolaca\' ne ca ngola runica ti mudu sica ti gueebe\'. Ra galaca\', rireeca\' ndaani\' mudu ne ruzulu ripapaca\' ne ca xhiahuiini\'ca\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',    'ced_audio'=>'a', 'ced_codigo'=>'<!--7 -->Ti nácame ti insecto bisiroobacabe la, grana qué randadi\' guibani pa qué gapa\' binni laame. Naquiiñe\' gápanu laame ne ca granizada ne nisaguiero\'. Ne zaqueca naquiiñe\' guidxiluchaahui\'nu ca xcaadxi insecto ni ró laame ne gunduxenu cá grana gui\'xhi\' ra guendandeelú lu guichibiaagueta ra nuume. Grana gui\'xhi\' la riguiñeme grana fina, ti naca nadá, ne ruuti guichibiaagueta pa qué gucueezanu laame. Naquiiñe\' cuunu le\' ne estaca o ne yagaguiichi ca guichibiaagueta ti zaca cá yuze ne ca manihuiini\' le\' qué góyaaca\' ca penca ne goca\' ca grana. Niru bizabilú ca binni Lula\' laacame la, laca gúpaca\' insecto xti\'ca\' ne rezá ne xhisaca gu\'xhu\' ne gui\'ri\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'90',    'ced_audio'=>'a', 'ced_codigo'=>'<!--8 --><h4>¿XI nannanu lu xquendanabanime?</h4>Rari\' ra Jardín Etnobiológico xti\' Lula\' biziidi\'du grana la bisirooba\' binni laacame ne ca guichibiaagueta ti guiquiiñe\'ca laame sica tiee lu xieguidiladica\' niru guibaniné ca binni ñaa ra gutaxtí ca guidxi ne niru naquiiñe\' manihuiini\'di\' guidie\'né lari. Rábidu guichibiaagueta “de Castilla” ne grana nabani yenécabecani lu nisado\' lu balaaga\' ra biaaxhacabe neza guete\' Guidxiro\' Zaguita ne bigaandacabe Sudamérica, ti zaca bi\'ni\'cabe tinteca lu ca región ni napa clima nabidxi ne nadxaadú sicasi Valle xti\' Lula\'. Raque guacani naxiñá\' ni dunabepe\' nga guyula\'dxi\' ca inca y ne xcaadxi Guidxi huala\'dxi\' nuu lu Andes. '],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'100',   'ced_audio'=>'a', 'ced_codigo'=>'<!--9 -->Ca guichiyooxho\' rini\'ca Lula\' nga guca\' ra jmá bidale grana niru guedandá ca europeo, Mixteca ne Velles Centrales nga guca\'ca\' ca ni biseendaca\' tinte Tenochtitlan, capital xti\' Mexica. Gudi\'disi beeda invasión europea la, ca guidxidi\' bi\'ni\'ruca\' xtale ne jmá nacha\'hui\' tinte bia\' xhonna gayuaa iza, bia\' ra ca inglés ne ca alemán bizuluca\' bi\'ni\'ca\' anilinas bia\' ra gudi\'di\'si ti guixhiaapa xhono gayuaa chupa lategande bichii iza. Bia\' lu chonna gayuaa iza, grana xti\' Lula\' nga ni guca\' ni jmá bisaca lu guendaridoo guidubi ndaani\' guidxilayú. Xhiiña\' guendaridale xti\'me bidii xtale bidxichi xquidxinu ne bidii guirooba\'ni ne zaca gácani guionna guidxi jmá naro\'ba\' ne xtale xhisaca lu Nueva España. Zaguitasi ne Puebla nga gucaca\' ca guidxi ni jmá naro\'ba\' didica\' lu Lula\'.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'200',   'ced_audio'=>'a', 'ced_codigo'=>'<!--10 -->Gadxesi nga sicasi tabaco, biziaa ne dxiña nite ni bidxiiba\' ca esclavo lu ca hacienda, xhiiña\' grana lu ná\' ca guidxi huala\'dxi\' nga biaanani, laaca\' nga gupaca\' ca guendabiaani\' nacha\'hui\' ne xhiiña\'do\' xti\' na\'ca\' bisidaleneca\' laacame. Xtalepe\' nga bidxichi bisaanane grana ca español, ni gupaca\' lu na\'ca\' ca guendaridoo lu guidubi naca guidxilayú. Runi ndi\' nga, rey ne virrey ne xcaadxi ca xaique dunabepe\' gúpaca\' ca guidxi xti\' guidxi Lula\', jmá que ca xcaadxi gudxi. Runi laani jmá que bia\' 70 % ca layú ni nuu Lula\' yanna nácani xti\' binniguidxi. '],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'300',   'ced_audio'=>'a', 'ced_codigo'=>'<!--11 -->Dxi Benito Juárez, napa chii ne chupa iza, guzá biaaxha Guelatao ne yendá Guidxi Lula\', yendabe ra lidxi lisaa Maza, ra biza\'nabe cayuni dxiiña\' sica sirvienta. Bizulube bi\'ni\'be dxiiña\' lu ti layú guichibiaagueta napa grana. Xtale iza gui\'di\', Juárez ni bibanibe dxi nácabe badunguiiuhuiini\' lu xhiiña\' insectodi\' yeneni laabe guini\' iquebe ca binnirutoo xti\' Lula\' biaacabe guendarapa bidxichi nagueenda ni rusaana grana ngueruni qué nizala\'dxi\'cabe nuyubicabe sica ñunicabe dxiiña\' ti nusidaleru\'cabe xpidxichicabe jmá.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'400',   'ced_audio'=>'a', 'ced_codigo'=>'<!--12 --><h4>¿Paraa nga riree tieedi\' ne xi ridieeneni?</h4>Hemolinfa lu ca insecto la, zedayacani sicasi rini ladinu ne sicasi rini xti\' xcaadxi mani\'. Hemolinfa xti\' grana la, nápani ácido carmínico, ti sustancia narenda ne nexhedxí ni runini gácani naxiñarini. ácido carmínico chupa nga sica rápani ne rulani grana: niru la, rusilani laame ne ca infección lu doxqui\'me. Guiropa la, ácido carmínico riquiiñe\'ni sica ti repelente nadipa\' ne ca birí ne xcaadxi insecto ni guedató laame.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'500',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 13-->Ra guiquiiñe\'ni sica tinte la, ácido carmínico nadipa\'ni jmá que xcaadxi tiee lu gubidxa ne nisa. Ra guidieené, zanda guidxaa tiee xtini: vinagre, xnisa limón ne guirá\' ni naí\' rusibánicani tiee xtini gácani naxiñanabiguitu, ne lejía xti\' giuu o dé la, ruchaani ra nácacani naxiñacahui ne racani nagugüi. Xti\' xhisaca xti\' grana nga rulani laanu ne gubidxa ni runiná guidiladinu, rulani laanu jmá que xcaadxi ca tiee.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'600',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 14-->Lula\' grana riquiiñe\'cabe laa guidie\'né lana ne seda, ácido carmínico ni nápani naguenda riguiidi\'ni ca fibra mani\'. Ca lisaa riguiba xti\' Teotitlán ne Santa Ana del Valle riquiiñe\'ca\' grana ti gutieenécani ca sarape ne ca tapete nacané laana, ne guidxi San Pedro Cajonos riquiiñe\'ni ti guidieeneni chal nacané seda huala\'dxi\'. Lu xtale guidxizá dxique ca gunaa nabé nga guca\' bizuudi\' bidieené grana lu ca saa, jmápeca nga ca gunaa ni cuchaganá\'. Zaqueca biquiiñe\'ni ti guidieeneni ca guendaró sicasi nicuatole, ti guendaró nanixe ni racané xuba\' ni rului\' ti gelatina laa. Gudubinaca Guidxi Zaguita, ca guetaguu dxiña ridieeca\' ne tiee naxiñaté lu xtiidxa\' guendaruzetenala\'dxi\' grana, riquiiñe\' ti qué gusisacacabe laa guetaguu zidi.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'700',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 15-->Grana guacani tiee ni jmá bisisaca ca binnirutiee ne xcaadxi binni ni napa guenda xti\' xcaadxi guidxi runi guiralú tiee ne bia\' xtipa ni rudii ácido carmínico. Zandape\'ca guininu grana xti\' guidxi Lula\' nga ni jmá naro\'ba\' ni huadii guidxi Zaguita lu arte ndaani\' guidubi guidxilayú.'],
            ['ced_autor'=>'1','ced_lengua'=>'8', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'800',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 16-->Rari\' ra Jardín Etnobiológico, lu beeu julio chupu guixhiaapa gande ne tapa iza. Bizuludu gupadu ne bisiroobadu caadxi grana fina, runi artista Édgar Jahir López Trujillo, bichi xtidu ni dunabepe\' nacha\'hui\' ladxido\'. Bizuhaadu chupa chonna penca xti\' guichibiaagueta xti\' Castilla lu ti ndaa layú riaapa\' ti zaca ganda gunibia\' ca binni redaganna laadu insectodi\', jmape\'ca nga guiraxixé\' ca xcuidi xti\' ca lidxi guendarusiidi\' ni reedaca'],

            //Grana4, Huave7
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'10',    'ced_audio'=>'a', 'ced_codigo'=>'<!--1a --> Mi chech nüik'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'20',    'ced_audio'=>'a', 'ced_codigo'=>'<!--4 --> <h4>Akualaats nej at miün mi nüt nej</h4>Nop nine nimal aaga mi chech nüik, atang wüx ombas nüik. Ngomatüch adam noik nine os, aton among adam noik nine osab lentej. Ajküw chech netsambüw, ndoj ajküw nchikiw ajientsüw wüx nerrar akualaajtsüw aaga nine mi chech nüik. Ajküw akualaats nine mok küy ajiürüw ombeayiw nejiw niüng andoy mi yow xiül ngüa mi kiej nimal.'],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'30',    'ced_audio'=>'a', 'ced_codigo'=>'<!--5 -->Aaga mi chech nüik ajiür gajpowüw akualaats nej, atangüw tixiül miün Argentina atüüch nenguien andüy Texas, a miün noik tatangüjchiw mixejchiiüts. Aagüy ajüik tatangüjchiüts xeyay neat tamong, tarriüjtats aaga manetam ikoots. Matangücheran mi chech nüik tarang xeyay najneaj, tambeol mi kambajats nawüw kawak oküiaj México, kos tüüch ikoots nakants nenchomüy lamajiür xeyay gajpowüw akoik miow neat. Asoik “nejinin mi chech nüik” kos ajlüy pálwüx atangüw tixiül. Atam nejiw mandoyiw miyow nüik atkiay apaküw. Ajlüy pálwüx ajiür ran ombas nej, nendüüchndüüch at miün tarrang, nganüy aaga nejinin mi chech nüik ajiür ombas atnej najndot, ran najndot, ngome nael chajkiaw.'  ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'70',    'ced_audio'=>'a', 'ced_codigo'=>'<!--6 --><h4>¿Nguiane apak?</h4>Aaga nejinin mi chech nüik atang wüx ombas natangücheran nüik, xiül atangücheran tiül México tanomb. Ajlüy noik ajaraüw mi nüt nej tiül Tipajteam “nopal San Gabriel” nganüy aaga al noik mi nüt nej “nopal de Castilla”, ngome nawüw España. Atangüjchiw ijpüw nüik nengüy tiül mi iüt Jardín küy, niüng apdom mijaw ngün nejiw nop nop, kos aop aaga nüik San Gabriel nelitlit nateaik, mi mbaj nej nakants maril, nganüy aop nüik Castilla najpos, mi mbaj nej maril. Mi sats ijpüw nüik laangomajiür kos a nipilan la majchiüw masap ombas, atkiay ngomajiür ael atangücheran mi chech nüik.'  ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'80',    'ced_audio'=>'a', 'ced_codigo'=>'<!--7 -->Ajküw natangücheran nüik niüng atangücheran nejinin mi chech nüik nerrin ombasüw atkiay nej nine mok küy, ndoj apdom majiürüch a miün niüng ngome nerrar xeyay: ngomaiük nerrar iüt at miün ngomaiük nekawüx nakind iüt. Ajtex kawüx wüx omal tiük kos ajmiük nakind. Tiül Tipajteam tanomb atangücheran tiül Mixteca, tiül najmiük iüt, tiül tak tiük aton tiül mbeay titiük.'  ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'90',    'ced_audio'=>'a', 'ced_codigo'=>'<!--8 --><h4>¿Nguineay ajüik ombas nej?</h4>Ajlüy nench, ajlüy nüx. Aaga nüx mi chech nüik newiling, ran ombas nej at miün nandan asapüy wüx nüik. Ngome xol xolüy kos najal ombeay nej, atnej nots narix ombeay najchow, asapüy nandan tiül omeats aop nüik. Aaga nench mi chech nüik ma nine nej nogomatüch adam nüx, ajiür mi lüm nej, apdom majlül, ngomapak xeyay, amiün ijpüw nüt. Al wijkiamoj nine nejiw nalitlit nakants ombasüw kos nganaw matüch ram ombasüw. Ajierüw oleajiw naag ajüiw wüx ombas nüik. Atkeay wüx teatangüw langom majüyiw kos apmajiërüw wüx ombasüw cer. Ajküw nüx wilinguiejow nganüy nench arang noik ombiüm atnej nine narix najchow. Wüx apmatang apmaw tiül ombiüm nej najlül.'  ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'100',   'ced_audio'=>'a', 'ced_codigo'=>'<!--9 -->Aagüy noik nine mok natangücheran, nejinin mi chech nüik ngomapak ndot ngomajlüy nipilan monjaw nej. Netam majiürüch wüx ajmiük napak ijchiür. At miün netam apalaran tembas palwüx mok ndea matiw aaga nine mok küy. At mïun ngondom majntsop palwüx mi chech nüik najlüy tixiül makiüb a nejinin ijpüw wüx nop nüik ngondom. Kos aaga mi chech nüik natang tixiül ambiy agga nejinin mi chech nüik, kos nerrin, at miün apdom mambiye nüik. Aaga nüik apalaran tiül ombiüm atnej otüeng korrül ayaküch sats atkiay ngo müt nej waküx, ngüa kiek kos netooch. Nipilan atajküw majneaj mi nüik nejiw, ngome amiün ayaj arangüw, mi nipilan Tipajteam at miün acheniw pom, candeal, arangüw rosar kos andiümüw nine mok küy.'  ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'200',   'ced_audio'=>'a', 'ced_codigo'=>'<!--10 --><h4>¿Kuane ajawats wüx nguineay tamongoch?</h4>Nengüy tiül Jardin Etnobiologico tiül Tipajteam lanajawan ngueniay aaga nine mi chech nüik küy tatangücheran makiüba nüik kos tayarich nenchomüy ombasaran, wüx ajküw nipilan nganaw marang mi najiütüw nejiw apiürüw naxiül pamapaküw tiül ajküw nine kambaj at miün wüx nganaw mayariw nine mi chech nüik manchomüw apixaw. Sapiüngan aaga nüik “de Castilla” akiüb a nine mi chech nüik aliün mapak wüx takiürab am tiül müx andojkiwe ndek miün kawak oküiaj México andüy kawak oküiaj America (Sudamérica), atkiay tapakücheran aaga nenchomüy kiaj tiül nerraar kambaj at miün niün ngome xeyay nerraar atnej tiül Tipajteam. Nenguiün ajküw incas, at miün ajküw mi kambaj los Andes tandiümüw a nakants kiaj.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'300',   'ced_audio'=>'a', 'ced_codigo'=>'<!--11 -->Ajküw tanomb nawiig andeak ajüik tiül Tipajteam ajlüy xeyay atangücheran aaga nine mi chech nüik küy wüx nganaw mapeayiwe europeos. Mixteca akiüb pinowan najmiük iüt nejiw ajkániün awüniw aaga nine mok nenchomüy küy majchiw Tenochtitlan, niüng ajlüyiw mexicas. Ndoj ngojniaj apiayiwe europeos, ajküw nine kambaj küy teleám miün mapaküjchiw aaga nenchomüy küy manajneaj taw tiül aroomb akoik miow neat, ndoj ajküw ingleses makiüb alemanes tarangüwa anilina tiül gajpopeak akoik miow ik miow gajpowüw neat(1850). Tiül aroomb akoik miow neat aaga nine mok küy tiül Tipajteam tajnap najneaj ajnap tiül meáwan kambaj. Tüüch majiür tomiün at miün tadam a kambaj tiül Nueva España. A miün kambaj México makiüb Puebla manadamüw andub miün Tipajteam.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'400',   'ced_audio'=>'a', 'ced_codigo'=>'<!--12 -->Tajlüy mi xiül xiig, mi xiül chicolüt at miün olam, apiürüw netiün andüy nipilan  ngomajiürüw poch nerangüw najiüt tiül nadamüy iüt niün apiürüch, aaga nine mi chech nüik tajlüy deam tewix nipilan nawüw tiül nine kambaj, niüng axomüw omeajtsüw nguineay najneaj apakücheran nine mok küy. Ajküw españoles taxomüw xeyay tomiün wüx, anüjpiw andüy meawan kambaj. Ajküw netaag mandar at miün monjiür najiüt tea majiürüw ajküw nine kambaj tiül Tipajteam. Nganüy xeyay mi iüt kambaj tiül Tipajteam comunal nejiw.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'500',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 13-->Wüx Benito Juarez, tajiür gajpik neat, tajüy miün Guelatao andüy Tipajteam, tapeay aniüngüw Maza, niüng Josefa mi koj nej nerang najiüt kiaj. Neje nine nench kia naw tiül tiük tarang najiüt tiül noik iüt niüng atangüjchiw nüik makiüb nine mi chech nüik. Tamong xeyay neat, tamong temal nej Juárez tapiüng ajküw monujpeay tiül Tipajteam lasap ombasüw ngomajiür nael anujpiw nine mi chech nüik, atkeay ngo mayambüw kuane al noik manüjpiw.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'600',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 14--><h4>¿Nguiane naw aaga nenchomüy, kuane alndom menchomanaag?</h4>Mi yow omeats aaga ajküw nine mok küy atnej kiej tiül ombasats, at miün atnej mi kiej nimal. Aaga mi yow omeats nine mi chech nüik ajiür nachiich mi nüt nej ácido carmínico, agüy üüch majtep akants. Aaga ácido carmínico ambeol mewüneay nine mi mok nüik ngomajiür nael nekoy tiül mi xiüt aons at miün ambeolnej mewüneay ngo müet nej chok ngüa palwüx nadam mok.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'700',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 15-->Nayarich atnej nenchomüy, aaga ácido carmínico ajiür najneaj neíük tiül atil teat nüt at miün tiül yow. Wüx menchom, apdom mangowücheran nguineay anchom: leaw nachiich, atnej mi yow lemoen apaküüch nakants ombas andüy tiül nakants maril, nganüy mi yow posoel ngüa ngwiat angowüch marang naét nakants andüy tiül nambeots. Aton ajiür al noik najneaj aaga nine mi chech nüik awün ikoots wüx ambel atil teat nüt wüx mitaajkats, ngome atnej altiül nenchomüy.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'700',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 16-->Tiül Tipajteam aaga nine mi chech nüik küy anchom milan sap akiiüb onts ombeay tajkoch, kos aaga ácido carmínico asapüy manajneaj wüx mi eed nimal. Nipilan monjüy monaw Teotitlan akiüb Santa Ana del Valle ayariwe nine mi chech nüik küy manchomüw leaw apixaw ajüyiw oküiaj milan sap, nganüye San Pedro Cajones ayariw manchomüw püy ajüyiw naag ons ombeay tajkoch. Tiül Xeyay kambaj asap ombasüw ajküw montaj asojkiw jal nenchomüy naag nine mi chech nüik wüx majlüy nangox nüt, wüx nop nüx mengoch owix. At miün tetamb nenchom nüeteran atnej nicoatol, noik nüeteran arangüch naag os naweal ajlüy. Tiül México, ajlüy nangan nitiül nanchoram najpos nakants leaw omeatsaran atkiay anchom nine mi chech nüik atkiay ajaraw ngün najtix nitiül.' ],
            ['ced_autor'=>'1','ced_lengua'=>'7', 'ced_url'=>'4', 'ced_jardin'=>'1','ced_titulo'=>'0','ced_order'=>'700',   'ced_audio'=>'a', 'ced_codigo'=>'<!-- 17-->Pech México andüy menkiaj palwüx kambaj, ajküw monchom nawiig tandiümüw a mi chech nüik kos xeyay najneaj anchom, najtep nakants ngua najpos. Apdom mandeakats mi chech nüik tiül Tipajteam tambeol xeyay México andüy tiül arte andüy meáwan kambaj. Nengüy tiül Jardín Etnobiologico lajngot natangüjchiün a nejinin nine mi chech nüik tiül ayaíw kaw tiül nimiow akoik miow nimiow pikiw neat (2024), Dios mangüy nej teat nenchom Édgar Jahir López Trujillo, najneaj omeats mbaleoy. Sapiüran akas aop nüik de Castilla niüng ngomael ajlüiw, atkeay ajküw nipilan apeayiw majawüw guetow ambeat atam nine mok küy, atkeaiy ajküw namix nine monkiajchay miünüw.' ],


            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
            // ['ced_autor'=>'1','ced_lengua'=>'2', 'ced_url'=>'', 'ced_jardin'=>'1','ced_titulo'=>'','ced_order'=>'',   'ced_audio'=>'', 'ced_codigo'=>''],
        ];

    foreach ($events as $event){
        SpCedulasModel::create($event);
    }
    }
}
